### ISSUE TITLE
Jugar sol

### ISSUE THREAD

**Issue by tonirc** [Triviacat/trivial#1]
Quan jugues sol, el joc no et permet jugar. El dau es mou, però no apareix cap pregunta.

**Comment by robertgarrigos** [comment]
El joc no està pensat per jugar sol. La pregunta surt a la pantalla d'algun dels altres jugadors. Al web on recollim les preguntes (https://preguntes.triviacat.site/jugueu) sí que pots jugar-hi sol, tot i que no hi ha tauler.
